server:
  port: 10004
spring:
  application:
    name: configService
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/suixin837/emconfig
          search-paths: /easymall
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka #eureka暴露接口，用于注册到eureka上