server:
  port: 10008
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
mybatis:
  configuration:
    cacheEnabled: false
    mapUnderscoreToCamelCase: true
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.jt.common.pojo
spring:
  application:
    name: searchservice
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5
    maxActive: 50
    maxIdle: 10
    minIdle: 5
    url: jdbc:mysql://suixin837.mysql.rds.aliyuncs.com:3306/easydb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: suixin837@ruoyi
    type: com.alibaba.druid.pool.DruidDataSource
  es:
    clusterName: my-application
    nodes: 106.13.46.193:9300,106.13.46.193:9301,106.13.46.193:9302
