server:
  port: 10006
spring:
  application:
    name: picservice
eureka:
  client:
    service-url:
      dafaultZone: http://localhost:8761/eureka
pic:
  pathDirPrefix: D://upload/
  urlPrefix: http://image.jt.com/